# Configuração do Dependabot para atualizações automáticas
version: 2
updates:
  # Atualizações do npm (Frontend)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "AluizioNunes"
    assignees:
      - "AluizioNunes"
    commit-message:
      prefix: "npm"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    ignore:
      # Ignorar atualizações de versões major que podem quebrar
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "typescript"
        update-types: ["version-update:semver-major"]

  # Atualizações do pip (Backend)
  - package-ecosystem: "pip"
    directory: "/Backend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "AluizioNunes"
    assignees:
      - "AluizioNunes"
    commit-message:
      prefix: "pip"
      include: "scope"
    labels:
      - "dependencies"
      - "backend"
    ignore:
      # Ignorar atualizações de versões major que podem quebrar
      - dependency-name: "fastapi"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pydantic"
        update-types: ["version-update:semver-major"]

  # Atualizações do Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "AluizioNunes"
    assignees:
      - "AluizioNunes"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    ignore:
      # Ignorar atualizações de versões major que podem quebrar
      - dependency-name: "node"
        update-types: ["version-update:semver-major"]
      - dependency-name: "python"
        update-types: ["version-update:semver-major"]
      - dependency-name: "postgres"
        update-types: ["version-update:semver-major"]

  # Atualizações do GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "AluizioNunes"
    assignees:
      - "AluizioNunes"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - "dependencies"
      - "ci-cd"

  # Atualizações do Composer (se houver)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "AluizioNunes"
    assignees:
      - "AluizioNunes"
    commit-message:
      prefix: "composer"
      include: "scope"
    labels:
      - "dependencies"
      - "php" 