version: '3.9'
services:
  db:
    image: postgres:17.5
    restart: always
    environment:
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: senha
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:8.0
    ports:
      - "6379:6379"
    restart: always

  backend:
    build: ./backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=postgresql://usuario:senha@db:5432/meubanco
      - APP_NAME=MeuProjetoBase
      - DEBUG=True
      - SECRET_KEY=troque-por-uma-chave-secreta
      - BACKEND_CORS_ORIGINS=http://localhost:3000
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"

  frontend:
    build: .
    command: npm start
    volumes:
      - .:/app
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata: 