version: '3.9'

############################
#  DOCKER COMPOSE - PROD   #
#  MODO SOMENTE TRAEFIK    #
############################

services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ=America/Manaus
      - TRAEFIK_ACME_EMAIL=${TRAEFIK_ACME_EMAIL:-base@itfact.com.br}
    command:
      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=base_network
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # ACME (Let's Encrypt)
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL:-base@itfact.com.br}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Dashboard
      - --api.dashboard=true
      - --api.insecure=true
      # Logs
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/BASE/volumes/traefik_data:/letsencrypt
    labels:
      - "traefik.enable=true"
      # Dashboard Config
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.entrypoints=web"
    networks:
      - base_network

# ---------------------------------------------------------
#  SERVIÇOS DESATIVADOS (comentados)
# ---------------------------------------------------------
#  grafana:
#    image: grafana/grafana:latest
#    # ...
#
#  loki:
#    image: grafana/loki:latest
#    # ...
#
#  frontend:
#    build: .
#    # ...
#
#  backend:
#    build: ./Backend
#    # ...
#
#  db:
#    image: postgres:17.5
#    # ...
#
#  redis:
#    image: redis:8.0-alpine
#    # ...
#
#  rabbitmq:
#    image: rabbitmq:4.1.2-management-alpine
#    # ...

networks:
  base_network:
    driver: bridge 
