version: '3.9'

############################
#  DOCKER COMPOSE - PROD   #
#  MODO SOMENTE TRAEFIK    #
############################

services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ=America/Manaus
      - TRAEFIK_ACME_EMAIL=${TRAEFIK_ACME_EMAIL:-base@itfact.com.br}
    command:
      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=base_network
      # Entrypoints
      - --entrypoints.http.address=:80
      - --entrypoints.https.address=:443
      - --entrypoints.https.http.tls=true
      # ACME (Let's Encrypt)
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Dashboard
      - --api.dashboard=true
      - --api.insecure=false
      # Logs
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/BASE/volumes/traefik_data:/letsencrypt
    labels:
      - "traefik.enable=true"
      # Basic Auth
      - "traefik.http.middlewares.traefik-auth.basicauth.users=BASE:$2y$05$p4R271GGBqBPdZiZsaAJ2eIuAvV38DSHLVbkP4SRr_1IovnHgkmty"
      # Redirect HTTP -> HTTPS
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.http-catchall.rule=HostRegexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=http"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      # Dashboard
      - "traefik.http.routers.dashboard.rule=Host(`${TRAEFIK_DASHBOARD_DOMAIN:-traefik.local}`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))"
      - "traefik.http.routers.dashboard.entrypoints=https"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=traefik-auth"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"
    networks:
      - base_network

# ---------------------------------------------------------
#  SERVIÇOS DESATIVADOS (comentados)
# ---------------------------------------------------------
#  grafana:
#    image: grafana/grafana:latest
#    # ...
#
#  loki:
#    image: grafana/loki:latest
#    # ...
#
#  frontend:
#    build: .
#    # ...
#
#  backend:
#    build: ./Backend
#    # ...
#
#  db:
#    image: postgres:17.5
#    # ...
#
#  redis:
#    image: redis:8.0-alpine
#    # ...
#
#  rabbitmq:
#    image: rabbitmq:4.1.2-management-alpine
#    # ...

networks:
  base_network:
    driver: bridge 
