version: '3.9'

services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=true
      - --entrypoints.web.address=:80
      - --log.level=INFO
    networks:
      - base_network

  frontend:
    build: .
    command: sh -c "npm run build && npm run preview -- --host 0.0.0.0 --port 3000"
    environment:
      - VITE_API_URL=http://10.10.255.111/api
    ports:
      - "3000:3000"
    networks:
      - base_network

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - /var/lib/docker/BASE/volumes/Backend/uploads_data:/app/uploads
    environment:
      - DBHOST=db
      - DBNAME=BASE
      - DBUSER=BASE
      - DBPASSWORD=BASE
      - DBSCHEMA=BASE
      - BACKEND_CORS_ORIGINS=http://10.10.255.111
    ports:
      - "8000:8000"
    networks:
      - base_network

  rabbitmq:
    image: rabbitmq:4.1.2-management-alpine
    hostname: rabbitmq
    volumes:
      - /var/lib/docker/BASE/volumes/rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=BASE
      - RABBITMQ_DEFAULT_PASS=BASE
    ports:
      - "15672:15672"
    networks:
      - base_network

  db:
    image: postgres:17.5
    volumes:
      - /var/lib/docker/BASE/volumes/Backend/pgsql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=BASE
      - POSTGRES_USER=BASE
      - POSTGRES_PASSWORD=BASE
      - POSTGRES_SCHEMA=BASE
    networks:
      - base_network

  redis:
    image: redis:8.0-alpine
    command: redis-server --requirepass BASE
    volumes:
      - /var/lib/docker/BASE/volumes/redis_data:/data
    networks:
      - base_network

networks:
  base_network:
    driver: bridge 
