version: '3.9'

services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --log.level=INFO
    networks:
      - base_network

  frontend:
    build: .
    command: sh -c "npm run build && npm run preview -- --host 0.0.0.0 --port 3000"
    environment:
      - VITE_API_URL=http://10.10.255.111/api
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`10.10.255.111`) && !PathPrefix(`/api`, `/grafana`, `/rabbitmq`, `/loki`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.priority=1"
    networks:
      - base_network

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - /var/lib/docker/BASE/volumes/Backend/uploads_data:/app/uploads
    environment:
      - DBHOST=db
      - DBNAME=BASE
      - DBUSER=BASE
      - DBPASSWORD=BASE
      - DBSCHEMA=BASE
      - BACKEND_CORS_ORIGINS=http://10.10.255.111
    ports:
      - "8001:8000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`10.10.255.111`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend.priority=10"
    networks:
      - base_network

  rabbitmq:
    image: rabbitmq:4.1.2-management-alpine
    hostname: rabbitmq
    volumes:
      - /var/lib/docker/BASE/volumes/rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=BASE
      - RABBITMQ_DEFAULT_PASS=BASE
    ports:
      - "15673:15672"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=Host(`10.10.255.111`) && PathPrefix(`/rabbitmq`)"
      - "traefik.http.routers.rabbitmq.entrypoints=web"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
      - "traefik.http.middlewares.rabbitmq-stripprefix.stripprefix.prefixes=/rabbitmq"
      - "traefik.http.routers.rabbitmq.middlewares=rabbitmq-stripprefix"
      - "traefik.http.routers.rabbitmq.priority=10"
    networks:
      - base_network

  db:
    image: postgres:17.5
    volumes:
      - /var/lib/docker/BASE/volumes/Backend/pgsql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=BASE
      - POSTGRES_USER=BASE
      - POSTGRES_PASSWORD=BASE
      - POSTGRES_SCHEMA=BASE
    networks:
      - base_network

  redis:
    image: redis:8.0-alpine
    command: redis-server --requirepass BASE
    volumes:
      - /var/lib/docker/BASE/volumes/redis_data:/data
    networks:
      - base_network

  grafana:
    image: grafana/grafana:latest
    user: "472:472"
    ports:
      - "3010:3010"
    volumes:
      - /var/lib/docker/BASE/volumes/grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=BASE
      - GF_SECURITY_ADMIN_PASSWORD=BASE
      - GF_SERVER_HTTP_PORT=3010
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`10.10.255.111`) && PathPrefix(`/grafana`)"
      - "traefik.http.routers.grafana.entrypoints=web"
      - "traefik.http.services.grafana.loadbalancer.server.port=3010"
      - "traefik.http.routers.grafana.middlewares=grafana-stripprefix"
      - "traefik.http.middlewares.grafana-stripprefix.stripprefix.prefixes=/grafana"
      - "traefik.http.routers.grafana.priority=10"
    networks:
      - base_network

  loki:
    image: grafana/loki:latest
    user: "1000:1000"
    command: -config.file=/etc/loki/local-config.yaml -server.http-listen-port=3100
    ports:
      - "3100:3100"
    volumes:
      - /var/lib/docker/BASE/volumes/loki_data:/loki
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.loki.rule=Host(`10.10.255.111`) && PathPrefix(`/loki`)"
      - "traefik.http.routers.loki.entrypoints=web"
      - "traefik.http.services.loki.loadbalancer.server.port=3100"
      - "traefik.http.routers.loki.priority=10"
    networks:
      - base_network

  n8n:
    image: n8nio/n8n:latest
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=BASE
      - N8N_BASIC_AUTH_PASSWORD=BASE
      - N8N_HOST=10.10.255.111
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://10.10.255.111/n8n/
      - GENERIC_TIMEZONE=America/Manaus
    volumes:
      - /var/lib/docker/BASE/volumes/n8n_data:/home/node/.n8n
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`10.10.255.111`) && PathPrefix(`/n8n`)"
      - "traefik.http.routers.n8n.entrypoints=web"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
      - "traefik.http.routers.n8n.middlewares=n8n-stripprefix"
      - "traefik.http.middlewares.n8n-stripprefix.stripprefix.prefixes=/n8n"
      - "traefik.http.routers.n8n.priority=10"
    networks:
      - base_network

  chatwoot:
    image: chatwoot/chatwoot:latest-ce
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      - INSTALLATION_NAME=BASE
      - SECRET_KEY_BASE=your-secret-key-base-here
      - FRONTEND_URL=http://10.10.255.111/chatwoot
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME=BASE
      - POSTGRES_PASSWORD=BASE
      - POSTGRES_DATABASE=chatwoot
      - REDIS_URL=redis://redis:6379/1
      - REDIS_PASSWORD=BASE
      - RAILS_ENV=production
      - NODE_ENV=production
    volumes:
      - /var/lib/docker/BASE/volumes/chatwoot_data:/app/storage
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chatwoot.rule=Host(`10.10.255.111`) && PathPrefix(`/chatwoot`)"
      - "traefik.http.routers.chatwoot.entrypoints=web"
      - "traefik.http.services.chatwoot.loadbalancer.server.port=3000"
      - "traefik.http.routers.chatwoot.middlewares=chatwoot-stripprefix"
      - "traefik.http.middlewares.chatwoot-stripprefix.stripprefix.prefixes=/chatwoot"
      - "traefik.http.routers.chatwoot.priority=10"
    networks:
      - base_network
    depends_on:
      - db
      - redis

networks:
  base_network:
    driver: bridge 
