version: '3.9'

############################
#  DOCKER COMPOSE - PROD   #
#  MODO SOMENTE TRAEFIK    #
############################

services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    command:
      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=base_network
      # Entrypoint HTTP
      - --entrypoints.web.address=:80
      # Dashboard API
      - --api.dashboard=true
      - --api.insecure=false
      # Logs
      - --log.level=INFO
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=BASE:$2y$05$p4R271GGBqBPdZiZsaAJ2eIuAvV38DSHLVbkP4SRr_1IovnHgkmty"
      - "traefik.http.routers.dashboard.rule=PathPrefix(`/dashboard`)"
      - "traefik.http.routers.dashboard.entrypoints=web"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.middlewares=traefik-auth"
      - "traefik.http.routers.dashboard.priority=30"
    networks:
      - base_network

# ---------------------------------------------------------
#  SERVIÇOS DESATIVADOS (comentados)
# ---------------------------------------------------------
#  grafana:
#    image: grafana/grafana:latest
#    # ...
#
#  loki:
#    image: grafana/loki:latest
#    # ...
#
#  frontend:
#    build: .
#    # ...
#
#  backend:
#    build: ./Backend
#    # ...
#
#  db:
#    image: postgres:17.5
#    # ...
#
#  redis:
#    image: redis:8.0-alpine
#    # ...
#
#  rabbitmq:
#    image: rabbitmq:4.1.2-management-alpine
#    # ...

networks:
  base_network:
    driver: bridge
    name: base_network 
