version: '3.9'

############################
#  DOCKER COMPOSE - PROD   #
#  MODO SOMENTE TRAEFIK    #
############################

services:
  traefik:
    image: traefik:v3.4
    container_name: traefik
    restart: unless-stopped
    environment:
      - TZ=America/Manaus
      - TRAEFIK_ACME_EMAIL=${TRAEFIK_ACME_EMAIL:-base@itfact.com.br}
    command:
      # Providers
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.docker.network=base_network
      # Entrypoints
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      # ACME (Let's Encrypt)
      - --certificatesresolvers.letsencrypt.acme.tlschallenge=true
      - --certificatesresolvers.letsencrypt.acme.email=${TRAEFIK_ACME_EMAIL:-base@itfact.com.br}
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      # Dashboard
      - --api.dashboard=true
      - --api.insecure=true
      # Logs
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/BASE/volumes/traefik_data:/letsencrypt
    labels:
      - "traefik.enable=true"
      # Dashboard Config
      - "traefik.http.routers.traefik.rule=PathPrefix(`/traefik`)"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.entrypoints=web"
      - "traefik.http.middlewares.traefik-stripprefix.stripprefix.prefixes=/traefik"
      - "traefik.http.routers.traefik.middlewares=traefik-stripprefix"
    networks:
      - base_network

# ---------------------------------------------------------
#  SERVIÇOS DESATIVADOS (comentados)
# ---------------------------------------------------------
  frontend:
    build: .
    command: sh -c "npm run build && npm run preview -- --host 0.0.0.0 --port 3000"
    environment:
      - VITE_API_URL=http://10.10.255.111/api
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`) && !PathPrefix(`/redis-commander`, `/api`, `/rabbitmq`, `/traefik`)"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
    networks:
      - base_network

  backend:
    build: 
      context: ./Backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - /var/lib/docker/BASE/volumes/Backend/uploads_data:/app/uploads
    environment:
      - DBHOST=db
      - DBNAME=BASE
      - DBUSER=BASE
      - DBPASSWORD=BASE
      - DBSCHEMA=BASE
      - BACKEND_CORS_ORIGINS=http://10.10.255.111
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8000"
    networks:
      - base_network

  rabbitmq:
    image: rabbitmq:4.1.2-management-alpine
    hostname: rabbitmq
    volumes:
      - /var/lib/docker/BASE/volumes/rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=BASE
      - RABBITMQ_DEFAULT_PASS=BASE
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rabbitmq.rule=PathPrefix(`/rabbitmq`)"
      - "traefik.http.routers.rabbitmq.entrypoints=web"
      - "traefik.http.services.rabbitmq.loadbalancer.server.port=15672"
      - "traefik.http.routers.rabbitmq.middlewares=rabbitmq-stripprefix"
      - "traefik.http.middlewares.rabbitmq-stripprefix.stripprefix.prefixes=/rabbitmq"
    networks:
      - base_network

  db:
    image: postgres:17.5
    volumes:
      - /var/lib/docker/BASE/volumes/Backend/pgsql_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=BASE
      - POSTGRES_USER=BASE
      - POSTGRES_PASSWORD=BASE
      - POSTGRES_SCHEMA=BASE
    networks:
      - base_network

  redis:
    image: redis:8.0-alpine
    command: redis-server --requirepass BASE
    volumes:
      - /var/lib/docker/BASE/volumes/redis_data:/data
    networks:
      - base_network

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=BASE
      - HTTP_USER=BASE
      - HTTP_PASSWORD=BASE
      - URL_PREFIX=/redis-commander
      - BASE_PATH=/redis-commander
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.redis-commander.rule=PathPrefix(`/redis-commander`)"
      - "traefik.http.routers.redis-commander.priority=100"
      - "traefik.http.routers.redis-commander.entrypoints=web"
      - "traefik.http.services.redis-commander.loadbalancer.server.port=8081"
    networks:
      - base_network

networks:
  base_network:
    driver: bridge 
